### ISSUE TITLE
A cover theme for regular expression book series 

### ISSUE THREAD

**Issue by atej** [learnbyexample/learn_js_regexp#1]
Hi Sundeep,

Thanks for this book.

I made some covers for your books on regular expressions. Please feel free to use them if you like them.

![cover_js](https://user-images.githubusercontent.com/13627431/89134723-eda92880-d544-11ea-90d5-db4a6e0e1070.jpg)

![cover_python](https://user-images.githubusercontent.com/13627431/89134724-f3067300-d544-11ea-9996-0202f0cd7b42.jpg)

![cover_ruby](https://user-images.githubusercontent.com/13627431/89134726-f568cd00-d544-11ea-845d-92e3e335c688.jpg)

**Comment by learnbyexample** [comment]
Hey, the covers are cool looking and very well done. But I'm not looking to change my covers.

I'd suggest to create a repo like this one https://github.com/arasatasaygin/openlogos and invite people who wish to have logo/cover/etc designed. Sites like https://standardebooks.org/ebooks may also accept book covers. Wish you the best :)

**Comment by atej** [comment]
Sure Sundeep,

Totally your call of course :) And thanks for pointing me to these links. Very interesting!

**Comment by learnbyexample** [comment]
@atej Just saw a free illustrations site and thought I'd share a few links I had bookmarked, might be useful to you

* https://github.com/LisaDziuba/Awesome-Design-Tools
* https://news.ycombinator.com/item?id=24048508
* https://news.ycombinator.com/item?id=20503612
* https://news.ycombinator.com/item?id=21858822
* https://news.ycombinator.com/item?id=23517394
* https://news.ycombinator.com/item?id=23525648
* https://news.ycombinator.com/item?id=23896856
* https://www.reddit.com/r/programming/comments/hum2mq/550_customizable_size_color_stroke_opensource_svg/
* https://thenounproject.com/
